basePath: /
host: localhost:8080
info:
  contact: {}
  description: Swagger Example.
  title: TimeEcho API
  version: "1.0"
paths:
  /echo:
    post:
      consumes:
      - application/json
      description: post example
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: post example
  /time:
    get:
      description: get time
      responses:
        "200":
          description: OK
      summary: get time example
      tags:
      - example
swagger: "2.0"
